### ISSUE TITLE
decoding momentum/sparkpost click tracking urls

### ISSUE THREAD

**Issue by miforbes** [tuck1s/sparkyPMTATracking#1]
The tools you are writing here seem to be part of a new system for engagement tracking, as described on your post https://www.sparkpost.com/blog/deploying-signals-for-on-premises-powermta-with-engagement-tracking-part-4/ .

Are there similar tools for dealing with existing momentum/sparkpost engagement tracking, such as those described in your post https://www.sparkpost.com/blog/deploying-signals-premises-momentum-integration-part-3/ ?

In particular, the engagement tracking encoding mechanism seems quite different in the two pieces of software. In your part-3 post, you have URLs such as:

http://momo.signalsdemo.trymsys.net:81/q/rCZ3YpEEJBOHGGI06Rw9OA~~/AAAAAQA~/RgRfOCDVPhdCCgAAVe1WXbth_QBSGHN0ZXZlLnR1Y2tAc3Bhcmtwb3N0LmNvbVgEAAAAAEEIAC6rdFwAAPoJUQQAAAAARwJ7fQ~~

But the example URLs for your linktool here are of the form:

http://localhost:8888/eJxUzLEOQiEMRuF3-WciGAaTTr4JwbaIUSKBMhnf_Ybxnv18P2Q2EBgOltb4gFDN-iTvraotfs8Lfxsc2nyml4AQdqJZHqqlhCDXGG9wGNw3VYbK_fT-jwAAAP__f2Mg1g==

As far as I can tell these are of a different encoding.

Do you know of software that decodes the first type of URL as above?

**Comment by tuck1s** [comment]
You're correct that the two tracking encodings (Momentum, and this project) are quite different. The Momentum encoding is not open-sourced, is more complex, and uses cryptographic methods.

**Comment by miforbes** [comment]
Are there no open-source documentation/tools then for decoding the Momentum links? I understand that the entire Momentum project may not be open.
